import { EnemyType } from '../types/game';

// Базовый класс врага
export interface EnemyClass {
  id: string;
  name: string;
  type: EnemyType;
  baseHealth: number;
  baseSpeed: number;
  baseReward: number;
  spawnDelay: number;
}

// Константы задержки спавна для разных типов врагов
const SPAWN_DELAY = {
  INFANTRY: 80,
  TANK_SMALL: 700,
  TANK_MEDIUM: 750,
  TANK_LARGE: 800,
} as const;

// ============================================
// Уровень 1 - 5 типов врагов (только пехота)
// ============================================
export const LEVEL_1_ENEMIES: EnemyClass[] = [
  {
    id: 'l1_infantry_1',
    name: 'Рекрут',
    type: EnemyType.INFANTRY,
    baseHealth: 10,
    baseSpeed: 60,
    baseReward: 10,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l1_infantry_2',
    name: 'Солдат',
    type: EnemyType.INFANTRY,
    baseHealth: 15,
    baseSpeed: 55,
    baseReward: 12,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l1_infantry_3',
    name: 'Разведчик',
    type: EnemyType.INFANTRY,
    baseHealth: 8,
    baseSpeed: 70,
    baseReward: 11,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l1_infantry_4',
    name: 'Ветеран',
    type: EnemyType.INFANTRY,
    baseHealth: 20,
    baseSpeed: 50,
    baseReward: 15,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l1_tank_small',
    name: 'Легкий транспорт',
    type: EnemyType.TANK_SMALL,
    baseHealth: 150,
    baseSpeed: 40,
    baseReward: 25,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
];

// ============================================
// Уровень 2 - 6 типов врагов (больше пехоты, появляются танки)
// ============================================
export const LEVEL_2_ENEMIES: EnemyClass[] = [
  {
    id: 'l2_infantry_1',
    name: 'Штурмовик',
    type: EnemyType.INFANTRY,
    baseHealth: 80,
    baseSpeed: 65,
    baseReward: 15,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l2_infantry_2',
    name: 'Гренадер',
    type: EnemyType.INFANTRY,
    baseHealth: 100,
    baseSpeed: 70,
    baseReward: 18,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l2_infantry_3',
    name: 'Коммандос',
    type: EnemyType.INFANTRY,
    baseHealth: 70,
    baseSpeed: 80,
    baseReward: 17,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l2_infantry_4',
    name: 'Элитный боец',
    type: EnemyType.INFANTRY,
    baseHealth: 120,
    baseSpeed: 60,
    baseReward: 20,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l2_tank_small_1',
    name: 'Бронетранспортер',
    type: EnemyType.TANK_SMALL,
    baseHealth: 200,
    baseSpeed: 45,
    baseReward: 30,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l2_tank_small_2',
    name: 'Разведывательный танк',
    type: EnemyType.TANK_SMALL,
    baseHealth: 180,
    baseSpeed: 50,
    baseReward: 28,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
];

// ============================================
// Уровень 3 - 7 типов врагов (баланс пехоты и танков)
// ============================================
export const LEVEL_3_ENEMIES: EnemyClass[] = [
  {
    id: 'l3_infantry_1',
    name: 'Тяжелая пехота',
    type: EnemyType.INFANTRY,
    baseHealth: 120,
    baseSpeed: 70,
    baseReward: 20,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l3_infantry_2',
    name: 'Штурмовая группа',
    type: EnemyType.INFANTRY,
    baseHealth: 140,
    baseSpeed: 75,
    baseReward: 22,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l3_tank_small',
    name: 'Легкий танк',
    type: EnemyType.TANK_SMALL,
    baseHealth: 180,
    baseSpeed: 55,
    baseReward: 35,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l3_tank_medium_1',
    name: 'Средний танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 300,
    baseSpeed: 50,
    baseReward: 40,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l3_tank_medium_2',
    name: 'Штурмовой танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 280,
    baseSpeed: 55,
    baseReward: 42,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l3_tank_medium_3',
    name: 'Бронированный транспорт',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 320,
    baseSpeed: 48,
    baseReward: 38,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l3_infantry_3',
    name: 'Специальный отряд',
    type: EnemyType.INFANTRY,
    baseHealth: 100,
    baseSpeed: 85,
    baseReward: 25,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
];

// ============================================
// Уровень 4 - 8 типов врагов (больше танков)
// ============================================
export const LEVEL_4_ENEMIES: EnemyClass[] = [
  {
    id: 'l4_infantry_1',
    name: 'Ударная группа',
    type: EnemyType.INFANTRY,
    baseHealth: 150,
    baseSpeed: 75,
    baseReward: 25,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l4_infantry_2',
    name: 'Быстрый отряд',
    type: EnemyType.INFANTRY,
    baseHealth: 130,
    baseSpeed: 90,
    baseReward: 28,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l4_tank_small',
    name: 'Усиленный легкий танк',
    type: EnemyType.TANK_SMALL,
    baseHealth: 250,
    baseSpeed: 60,
    baseReward: 40,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l4_tank_medium_1',
    name: 'Боевой танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 400,
    baseSpeed: 55,
    baseReward: 50,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l4_tank_medium_2',
    name: 'Осадный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 450,
    baseSpeed: 50,
    baseReward: 48,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l4_tank_medium_3',
    name: 'Скоростной танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 350,
    baseSpeed: 60,
    baseReward: 52,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l4_tank_large_1',
    name: 'Тяжелый танк',
    type: EnemyType.TANK_LARGE,
    baseHealth: 600,
    baseSpeed: 45,
    baseReward: 65,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l4_infantry_3',
    name: 'Элитный десант',
    type: EnemyType.INFANTRY,
    baseHealth: 200,
    baseSpeed: 80,
    baseReward: 30,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
];

// ============================================
// Уровень 5 - 9 типов врагов (больше танков)
// ============================================
export const LEVEL_5_ENEMIES: EnemyClass[] = [
  {
    id: 'l5_infantry_1',
    name: 'Отряд спецназа',
    type: EnemyType.INFANTRY,
    baseHealth: 200,
    baseSpeed: 80,
    baseReward: 30,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l5_infantry_2',
    name: 'Бронированная пехота',
    type: EnemyType.INFANTRY,
    baseHealth: 250,
    baseSpeed: 75,
    baseReward: 32,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
  {
    id: 'l5_tank_medium_1',
    name: 'Продвинутый средний танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 500,
    baseSpeed: 60,
    baseReward: 60,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l5_tank_medium_2',
    name: 'Маневренный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 450,
    baseSpeed: 65,
    baseReward: 58,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l5_tank_large_1',
    name: 'Супертяжелый танк',
    type: EnemyType.TANK_LARGE,
    baseHealth: 700,
    baseSpeed: 50,
    baseReward: 70,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l5_tank_large_2',
    name: 'Боевой Мастодонт',
    type: EnemyType.TANK_LARGE,
    baseHealth: 800,
    baseSpeed: 48,
    baseReward: 75,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l5_tank_large_3',
    name: 'Штурмовой колосс',
    type: EnemyType.TANK_LARGE,
    baseHealth: 750,
    baseSpeed: 52,
    baseReward: 72,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l5_tank_medium_3',
    name: 'Ураганный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 480,
    baseSpeed: 58,
    baseReward: 55,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l5_infantry_3',
    name: 'Молниеносный отряд',
    type: EnemyType.INFANTRY,
    baseHealth: 180,
    baseSpeed: 95,
    baseReward: 35,
    spawnDelay: SPAWN_DELAY.INFANTRY,
  },
];

// ============================================
// Уровень 6 - 12 типов врагов (только танки)
// ============================================
export const LEVEL_6_ENEMIES: EnemyClass[] = [
  {
    id: 'l6_tank_small_1',
    name: 'Штурмовой раннер',
    type: EnemyType.TANK_SMALL,
    baseHealth: 300,
    baseSpeed: 70,
    baseReward: 45,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l6_tank_small_2',
    name: 'Быстрый перехватчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 280,
    baseSpeed: 75,
    baseReward: 42,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l6_tank_medium_1',
    name: 'Усиленный боевой танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 550,
    baseSpeed: 62,
    baseReward: 65,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l6_tank_medium_2',
    name: 'Огневая поддержка',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 600,
    baseSpeed: 58,
    baseReward: 68,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l6_tank_medium_3',
    name: 'Скоростной крейсер',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 520,
    baseSpeed: 68,
    baseReward: 62,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l6_tank_large_1',
    name: 'Тяжелый разрушитель',
    type: EnemyType.TANK_LARGE,
    baseHealth: 900,
    baseSpeed: 55,
    baseReward: 80,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l6_tank_large_2',
    name: 'Бронированный бегемот',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1000,
    baseSpeed: 52,
    baseReward: 85,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l6_tank_large_3',
    name: 'Железная крепость',
    type: EnemyType.TANK_LARGE,
    baseHealth: 950,
    baseSpeed: 50,
    baseReward: 82,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l6_tank_large_4',
    name: 'Стальной титан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 850,
    baseSpeed: 58,
    baseReward: 78,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l6_tank_large_5',
    name: 'Мобильный бункер',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1100,
    baseSpeed: 48,
    baseReward: 88,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l6_tank_medium_4',
    name: 'Ударная волна',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 580,
    baseSpeed: 65,
    baseReward: 70,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l6_tank_small_3',
    name: 'Молниеносный танк',
    type: EnemyType.TANK_SMALL,
    baseHealth: 320,
    baseSpeed: 80,
    baseReward: 48,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
];

// ============================================
// Уровень 7 - 14 типов врагов (только танки)
// ============================================
export const LEVEL_7_ENEMIES: EnemyClass[] = [
  {
    id: 'l7_tank_small_1',
    name: 'Легкий разведчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 350,
    baseSpeed: 85,
    baseReward: 50,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l7_tank_small_2',
    name: 'Скоростной налетчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 330,
    baseSpeed: 90,
    baseReward: 52,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l7_tank_medium_1',
    name: 'Модернизированный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 650,
    baseSpeed: 70,
    baseReward: 75,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l7_tank_medium_2',
    name: 'Боевой страж',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 700,
    baseSpeed: 68,
    baseReward: 78,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l7_tank_medium_3',
    name: 'Огненный дракон',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 680,
    baseSpeed: 72,
    baseReward: 76,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l7_tank_medium_4',
    name: 'Штурмовой авангард',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 720,
    baseSpeed: 65,
    baseReward: 80,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l7_tank_large_1',
    name: 'Супертяжелый гладиатор',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1200,
    baseSpeed: 60,
    baseReward: 95,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_large_2',
    name: 'Железный левиафан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1300,
    baseSpeed: 58,
    baseReward: 100,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_large_3',
    name: 'Бронированный колосс',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1250,
    baseSpeed: 62,
    baseReward: 98,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_large_4',
    name: 'Стальной монолит',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1150,
    baseSpeed: 65,
    baseReward: 92,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_large_5',
    name: 'Мега-разрушитель',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1400,
    baseSpeed: 55,
    baseReward: 105,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_large_6',
    name: 'Неудержимый джаггернаут',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1350,
    baseSpeed: 57,
    baseReward: 102,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l7_tank_medium_5',
    name: 'Плазменный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 750,
    baseSpeed: 70,
    baseReward: 82,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l7_tank_small_3',
    name: 'Ураганный рейдер',
    type: EnemyType.TANK_SMALL,
    baseHealth: 380,
    baseSpeed: 95,
    baseReward: 55,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
];

// ============================================
// Уровень 8 - 16 типов врагов (только танки)
// ============================================
export const LEVEL_8_ENEMIES: EnemyClass[] = [
  {
    id: 'l8_tank_small_1',
    name: 'Элитный разведчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 400,
    baseSpeed: 95,
    baseReward: 58,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l8_tank_small_2',
    name: 'Молниеносный штурмовик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 420,
    baseSpeed: 100,
    baseReward: 60,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l8_tank_small_3',
    name: 'Быстрая атака',
    type: EnemyType.TANK_SMALL,
    baseHealth: 380,
    baseSpeed: 105,
    baseReward: 62,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l8_tank_medium_1',
    name: 'Продвинутый боевой танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 800,
    baseSpeed: 75,
    baseReward: 88,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l8_tank_medium_2',
    name: 'Тяжелый крейсер',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 850,
    baseSpeed: 72,
    baseReward: 90,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l8_tank_medium_3',
    name: 'Ионный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 820,
    baseSpeed: 78,
    baseReward: 92,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l8_tank_medium_4',
    name: 'Энергетический страж',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 780,
    baseSpeed: 80,
    baseReward: 85,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l8_tank_medium_5',
    name: 'Огненный ураган',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 900,
    baseSpeed: 70,
    baseReward: 95,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l8_tank_large_1',
    name: 'Супермассивный танк',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1500,
    baseSpeed: 65,
    baseReward: 110,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_2',
    name: 'Титанический разрушитель',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1600,
    baseSpeed: 63,
    baseReward: 115,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_3',
    name: 'Кибернетический колосс',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1550,
    baseSpeed: 68,
    baseReward: 112,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_4',
    name: 'Плазменный бегемот',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1700,
    baseSpeed: 60,
    baseReward: 120,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_5',
    name: 'Ядерный титан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1650,
    baseSpeed: 62,
    baseReward: 118,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_6',
    name: 'Мега-джаггернаут',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1800,
    baseSpeed: 58,
    baseReward: 125,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_large_7',
    name: 'Неразрушимый страж',
    type: EnemyType.TANK_LARGE,
    baseHealth: 1750,
    baseSpeed: 65,
    baseReward: 122,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l8_tank_medium_6',
    name: 'Квантовый воин',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 950,
    baseSpeed: 75,
    baseReward: 98,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
];

// ============================================
// Уровень 9 - 18 типов врагов (только танки)
// ============================================
export const LEVEL_9_ENEMIES: EnemyClass[] = [
  {
    id: 'l9_tank_small_1',
    name: 'Гипер-разведчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 450,
    baseSpeed: 105,
    baseReward: 65,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l9_tank_small_2',
    name: 'Квантовый перехватчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 480,
    baseSpeed: 110,
    baseReward: 68,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l9_tank_small_3',
    name: 'Суперскоростной рейдер',
    type: EnemyType.TANK_SMALL,
    baseHealth: 420,
    baseSpeed: 115,
    baseReward: 70,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l9_tank_medium_1',
    name: 'Элитный боевой танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1000,
    baseSpeed: 80,
    baseReward: 105,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_medium_2',
    name: 'Кибер-крейсер',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1050,
    baseSpeed: 78,
    baseReward: 108,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_medium_3',
    name: 'Нейронный штурмовик',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 980,
    baseSpeed: 85,
    baseReward: 102,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_medium_4',
    name: 'Темная материя',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1100,
    baseSpeed: 75,
    baseReward: 110,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_medium_5',
    name: 'Антиматерия',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1020,
    baseSpeed: 82,
    baseReward: 106,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_medium_6',
    name: 'Плазменный вихрь',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1150,
    baseSpeed: 72,
    baseReward: 112,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l9_tank_large_1',
    name: 'Ультра-массивный танк',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2000,
    baseSpeed: 70,
    baseReward: 130,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_2',
    name: 'Апокалиптический бегемот',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2100,
    baseSpeed: 68,
    baseReward: 135,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_3',
    name: 'Омега-разрушитель',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2050,
    baseSpeed: 72,
    baseReward: 132,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_4',
    name: 'Кибер-левиафан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2200,
    baseSpeed: 65,
    baseReward: 140,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_5',
    name: 'Гипер-колосс',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2150,
    baseSpeed: 67,
    baseReward: 138,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_6',
    name: 'Финальный страж',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2300,
    baseSpeed: 63,
    baseReward: 145,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_7',
    name: 'Нано-титан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2250,
    baseSpeed: 70,
    baseReward: 142,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_8',
    name: 'Экстремальный джаггернаут',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2400,
    baseSpeed: 62,
    baseReward: 150,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l9_tank_large_9',
    name: 'Абсолютная крепость',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2350,
    baseSpeed: 68,
    baseReward: 148,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
];

// ============================================
// Уровень 10 - 20 типов врагов + БОСС (только танки)
// ============================================
export const LEVEL_10_ENEMIES: EnemyClass[] = [
  {
    id: 'l10_tank_small_1',
    name: 'Финальный разведчик',
    type: EnemyType.TANK_SMALL,
    baseHealth: 500,
    baseSpeed: 115,
    baseReward: 75,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l10_tank_small_2',
    name: 'Абсолютный рейдер',
    type: EnemyType.TANK_SMALL,
    baseHealth: 520,
    baseSpeed: 120,
    baseReward: 78,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l10_tank_small_3',
    name: 'Предельная скорость',
    type: EnemyType.TANK_SMALL,
    baseHealth: 480,
    baseSpeed: 125,
    baseReward: 80,
    spawnDelay: SPAWN_DELAY.TANK_SMALL,
  },
  {
    id: 'l10_tank_medium_1',
    name: 'Легендарный танк',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1200,
    baseSpeed: 85,
    baseReward: 120,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_medium_2',
    name: 'Мифический воин',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1250,
    baseSpeed: 82,
    baseReward: 125,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_medium_3',
    name: 'Божественный страж',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1180,
    baseSpeed: 88,
    baseReward: 118,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_medium_4',
    name: 'Хаос-генератор',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1300,
    baseSpeed: 80,
    baseReward: 128,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_medium_5',
    name: 'Вихрь разрушения',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1220,
    baseSpeed: 86,
    baseReward: 122,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_medium_6',
    name: 'Энергия вечности',
    type: EnemyType.TANK_MEDIUM,
    baseHealth: 1350,
    baseSpeed: 78,
    baseReward: 130,
    spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
  },
  {
    id: 'l10_tank_large_1',
    name: 'Максимальный разрушитель',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2500,
    baseSpeed: 75,
    baseReward: 160,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_2',
    name: 'Предельный бегемот',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2600,
    baseSpeed: 73,
    baseReward: 165,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_3',
    name: 'Судный день',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2550,
    baseSpeed: 77,
    baseReward: 162,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_4',
    name: 'Армагеддон',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2700,
    baseSpeed: 70,
    baseReward: 170,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_5',
    name: 'Апокалипсис',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2650,
    baseSpeed: 72,
    baseReward: 168,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_6',
    name: 'Вечный колосс',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2800,
    baseSpeed: 68,
    baseReward: 175,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_7',
    name: 'Бесконечный титан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2750,
    baseSpeed: 75,
    baseReward: 172,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_8',
    name: 'Космический левиафан',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2900,
    baseSpeed: 67,
    baseReward: 180,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_9',
    name: 'Непобедимый страж',
    type: EnemyType.TANK_LARGE,
    baseHealth: 2850,
    baseSpeed: 73,
    baseReward: 178,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  {
    id: 'l10_tank_large_10',
    name: 'Легенда разрушения',
    type: EnemyType.TANK_LARGE,
    baseHealth: 3000,
    baseSpeed: 70,
    baseReward: 185,
    spawnDelay: SPAWN_DELAY.TANK_LARGE,
  },
  // ФИНАЛЬНЫЙ БОСС
  {
    id: 'l10_boss',
    name: 'ИМПЕРАТОР РАЗРУШЕНИЯ',
    type: EnemyType.TANK_LARGE,
    baseHealth: 10000,
    baseSpeed: 50,
    baseReward: 1000,
    spawnDelay: 0,
  },
];

// Экспорт всех классов врагов по уровням
export const ENEMY_CLASSES_BY_LEVEL: Record<number, EnemyClass[]> = {
  1: LEVEL_1_ENEMIES,
  2: LEVEL_2_ENEMIES,
  3: LEVEL_3_ENEMIES,
  4: LEVEL_4_ENEMIES,
  5: LEVEL_5_ENEMIES,
  6: LEVEL_6_ENEMIES,
  7: LEVEL_7_ENEMIES,
  8: LEVEL_8_ENEMIES,
  9: LEVEL_9_ENEMIES,
  10: LEVEL_10_ENEMIES,
};
