import type { LevelConfig } from '../types/game';
import { EnemyType } from '../types/game';

// Константы задержки спавна для разных типов врагов
const SPAWN_DELAY = {
  INFANTRY: 80,
  TANK_SMALL: 700,
  TANK_MEDIUM: 750,
  TANK_LARGE: 800,
} as const;

// Создаём 10 уровней сложности с прогрессивным увеличением сложности
export const LEVELS: LevelConfig[] = [
  // Уровень 1 - Обучение
  {
    level: 1,
    startingMoney: 3000,
    startingLives: 20,
    waves: [
      {
        enemyCount: 40,
        enemyLevel: 1,
        enemyHealth: 10,
        enemySpeed: 60,
        enemyReward: 10,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 1,
        enemyHealth: 150,
        enemySpeed: 40,
        enemyReward: 25,
        spawnDelay: SPAWN_DELAY.TANK_SMALL,
        enemyType: EnemyType.TANK_SMALL,
      },
    ],
  },
  // Уровень 2
  {
    level: 2,
    startingMoney: 350,
    startingLives: 20,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 2,
        enemyHealth: 80,
        enemySpeed: 65,
        enemyReward: 15,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 2,
        enemyHealth: 200,
        enemySpeed: 45,
        enemyReward: 30,
        spawnDelay: SPAWN_DELAY.TANK_SMALL,
        enemyType: EnemyType.TANK_SMALL,
      },
      {
        enemyCount: 30,
        enemyLevel: 2,
        enemyHealth: 100,
        enemySpeed: 70,
        enemyReward: 18,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
    ],
  },
  // Уровень 3
  {
    level: 3,
    startingMoney: 400,
    startingLives: 18,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 3,
        enemyHealth: 120,
        enemySpeed: 70,
        enemyReward: 20,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 3,
        enemyHealth: 300,
        enemySpeed: 50,
        enemyReward: 40,
        spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
        enemyType: EnemyType.TANK_MEDIUM,
      },
      {
        enemyCount: 20,
        enemyLevel: 3,
        enemyHealth: 180,
        enemySpeed: 55,
        enemyReward: 35,
        spawnDelay: SPAWN_DELAY.TANK_SMALL,
        enemyType: EnemyType.TANK_SMALL,
      },
    ],
  },
  // Уровень 4
  {
    level: 4,
    startingMoney: 450,
    startingLives: 18,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 4,
        enemyHealth: 150,
        enemySpeed: 75,
        enemyReward: 25,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 4,
        enemyHealth: 400,
        enemySpeed: 55,
        enemyReward: 50,
        spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
        enemyType: EnemyType.TANK_MEDIUM,
      },
      {
        enemyCount: 30,
        enemyLevel: 4,
        enemyHealth: 200,
        enemySpeed: 80,
        enemyReward: 30,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
    ],
  },
  // Уровень 5
  {
    level: 5,
    startingMoney: 500,
    startingLives: 15,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 5,
        enemyHealth: 200,
        enemySpeed: 80,
        enemyReward: 30,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 5,
        enemyHealth: 500,
        enemySpeed: 60,
        enemyReward: 60,
        spawnDelay: SPAWN_DELAY.TANK_MEDIUM,
        enemyType: EnemyType.TANK_MEDIUM,
      },
      {
        enemyCount: 30,
        enemyLevel: 5,
        enemyHealth: 250,
        enemySpeed: 85,
        enemyReward: 35,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 20,
        enemyLevel: 5,
        enemyHealth: 600,
        enemySpeed: 65,
        enemyReward: 70,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
    ],
  },
  // Уровень 6
  {
    level: 6,
    startingMoney: 550,
    startingLives: 15,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 6,
        enemyHealth: 280,
        enemySpeed: 85,
        enemyReward: 35,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 6,
        enemyHealth: 700,
        enemySpeed: 65,
        enemyReward: 75,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
    ],
  },
  // Уровень 7
  {
    level: 7,
    startingMoney: 600,
    startingLives: 12,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 7,
        enemyHealth: 350,
        enemySpeed: 90,
        enemyReward: 40,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 7,
        enemyHealth: 850,
        enemySpeed: 70,
        enemyReward: 85,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
      {
        enemyCount: 30,
        enemyLevel: 7,
        enemyHealth: 400,
        enemySpeed: 95,
        enemyReward: 45,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 20,
        enemyLevel: 7,
        enemyHealth: 1000,
        enemySpeed: 75,
        enemyReward: 95,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
    ],
  },
  // Уровень 8
  {
    level: 8,
    startingMoney: 650,
    startingLives: 12,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 8,
        enemyHealth: 450,
        enemySpeed: 95,
        enemyReward: 50,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 8,
        enemyHealth: 1200,
        enemySpeed: 75,
        enemyReward: 100,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
      {
        enemyCount: 30,
        enemyLevel: 8,
        enemyHealth: 500,
        enemySpeed: 100,
        enemyReward: 55,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
    ],
  },
  // Уровень 9
  {
    level: 9,
    startingMoney: 700,
    startingLives: 10,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 9,
        enemyHealth: 550,
        enemySpeed: 100,
        enemyReward: 60,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 9,
        enemyHealth: 1500,
        enemySpeed: 80,
        enemyReward: 120,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
      {
        enemyCount: 30,
        enemyLevel: 9,
        enemyHealth: 650,
        enemySpeed: 105,
        enemyReward: 65,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 20,
        enemyLevel: 9,
        enemyHealth: 1800,
        enemySpeed: 85,
        enemyReward: 130,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
    ],
  },
  // Уровень 10 - Финальный босс
  {
    level: 10,
    startingMoney: 750,
    startingLives: 10,
    waves: [
      {
        enemyCount: 60,
        enemyLevel: 10,
        enemyHealth: 700,
        enemySpeed: 105,
        enemyReward: 70,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 30,
        enemyLevel: 10,
        enemyHealth: 2000,
        enemySpeed: 85,
        enemyReward: 140,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
      {
        enemyCount: 30,
        enemyLevel: 10,
        enemyHealth: 850,
        enemySpeed: 110,
        enemyReward: 80,
        spawnDelay: SPAWN_DELAY.INFANTRY,
        enemyType: EnemyType.INFANTRY,
      },
      {
        enemyCount: 20,
        enemyLevel: 10,
        enemyHealth: 2500,
        enemySpeed: 90,
        enemyReward: 150,
        spawnDelay: SPAWN_DELAY.TANK_LARGE,
        enemyType: EnemyType.TANK_LARGE,
      },
      {
        enemyCount: 1,
        enemyLevel: 10,
        enemyHealth: 8000,
        enemySpeed: 50,
        enemyReward: 500,
        spawnDelay: 0,
        enemyType: EnemyType.TANK_LARGE,
      },
    ],
  },
];

// Путь для врагов (зигзагообразный) - с учетом паддинга
const PADDING = 30;
export const DEFAULT_PATH = [
  { x: PADDING, y: 100 + PADDING },
  { x: 200 + PADDING, y: 100 + PADDING },
  { x: 200 + PADDING, y: 300 + PADDING },
  { x: 500 + PADDING, y: 300 + PADDING },
  { x: 500 + PADDING, y: 100 + PADDING },
  { x: 700 + PADDING, y: 100 + PADDING },
  { x: 700 + PADDING, y: 500 + PADDING },
  { x: 770 + PADDING, y: 500 + PADDING },
];
